name: tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  code-check:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.3.2
    - name: set up Python 3.8
      uses: actions/setup-python@v2.1.4
      with:
        python-version: 3.8
    - name: install requirements
      run: pip install ".[tests]"
    - name: check formatting
      run: pre-commit run --all-files
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
        pyv: ["3.7", "3.8", "3.9"]
    steps:
    - uses: actions/checkout@v2.3.2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.pyv }}
    - name: install
      shell: bash -l {0}
      run: pip install ".[tests]"
    - name: install libomp
      # required for xgboost
      if: runner.os == 'macOS'
      shell: bash -l {0}
      run: conda install libgomp -c conda-forge
    - name: run tests
      shell: bash -l {0}
      run: pytest -v --cov dvclive --cov-report=xml
    - name: upload coverage report
      uses: codecov/codecov-action@v1.0.13
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
