name: tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  code-check:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.3.2
    - name: set up Python 3.8
      uses: actions/setup-python@v2.1.4
      with:
        python-version: 3.8
    - name: install requirements
      run: pip install ".[tests]" collective.checkdocs --use-deprecated=legacy-resolver
    - name: Check README
      run: python setup.py checkdocs
    - name: check formatting
      run: pre-commit run --all-files
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
        pyv: ["3.7", "3.8", "3.9"]
    steps:
    - uses: actions/checkout@v2.3.2
    - name: set up python
      uses: actions/setup-python@v2.1.4
      with:
        python-version: ${{ matrix.pyv }}
    - name: install
      run: |
        pip install wheel
        # https://github.com/PyTorchLightning/metrics/issues/770
        pip install torchmetrics < 0.7.0
        pip install ".[tests]" --use-deprecated=legacy-resolver
    - name: install libomp
      # required for xgboost
      if: runner.os == 'macOS'
      run: |
        wget https://raw.githubusercontent.com/Homebrew/homebrew-core/679923b4eb48a8dc7ecc1f05d06063cd79b3fc00/Formula/libomp.rb -O $(find $(brew --repository) -name libomp.rb)
        brew install ninja libomp
        brew pin libomp        
    - name: run tests
      run: py.test -v --cov dvclive --cov-report=xml
    - name: upload coverage report
      uses: codecov/codecov-action@v1.0.13
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
